---
- hosts: localhost
  connection: local
  vars_files:
    - /home/ec2-user/sg_task/ansible_playbook/vars.yml
  roles:
    - security_group
    - launch_instance


- hosts: newly_created_instance
  remote_user: ec2-user
  roles:
    - deploy_web_application